In [1]:
import pandas as pd
data=pd.read_csv('fmea.csv')

In [2]:
data.head(84)

,Unnamed: 0,Unnamed: 1,MNB,BNB,GNB,DTC,LOGR,KNN,SVCL,SVCLP,SVCR,BAGK,BAGNB,BAGL,BAGD
0,ALM,black,0.341880,0.054795,0.547771,0.384615,0.544000,0.517986,0.542636,0.573427,0.468468,0.528000,0.341880,0.554745,0.343434
1,NaN,celery,0.000000,0.461773,0.367868,0.338677,0.069705,0.332714,0.000000,0.127273,0.127273,0.227907,0.000000,0.127273,0.365138
2,NaN,C python,0.764651,0.765471,0.743732,0.679426,0.763807,0.683099,0.766076,0.758231,0.764925,0.721133,0.764651,0.763975,0.700000
3,NaN,django-rest-framework,0.811060,0.803101,0.742754,0.760563,0.811060,0.773196,0.811060,0.811060,0.811060,0.797428,0.811060,0.811060,0.770833
4,NaN,jax,0.760697,0.781651,0.790378,0.752809,0.778547,0.705645,0.773196,0.776271,0.776632,0.776173,0.756672,0.786942,0.764168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,NaN,radash,0.000000,0.000000,0.173913,0.280543,0.067568,0.252427,0.000000,0.105960,0.105960,0.182796,0.000000,0.067568,0.326360
80,NaN,scrapy,0.914676,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.865455,0.837500,0.992593,0.980989
81,NaN,spaCy,0.827373,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.962422,0.781811,0.946465,1.000000
82,NaN,transformers,0.000000,0.000000,0.350975,0.383292,0.244224,0.310078,0.239203,0.236842,0.220736,0.418367,0.000000,0.153846,0.380711
83,NaN,yolov5,0.787313,0.786181,0.746747,0.765358,0.787313,0.738366,0.787313,0.787313,0.787313,0.776585,0.787313,0.787313,0.763343